[project]
name = "yndx-2-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.135.1",
    "pydantic-settings>=2.11.0",
    "psycopg[binary]>=3.2.12",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.43",
    "bcrypt>=4.3.0",
    "PyJWT>=2.10.1",
    "uvicorn>=0.35.0",
    "jwt>=1.4.0",
]
[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.hatch.build.targets.sdist]
include = [
    "/app",
    "/README.md",
    "/pyproject.toml",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
